#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only WITH LicenseRef-limina-exception
# Copyright © 2026 Gustavo Noronha Silva

# Build kk-linear-ds-vk: compile the embedded shaders to SPIR-V headers, link against
# the Homebrew Vulkan loader. Run with VK_ICD_FILENAMES pointing at the KK build:
#   VK_ICD_FILENAMES=$(ls /Volumes/mesa-cs/build-kk/src/kosmickrisp/vulkan/*.json) \
#     ./kk-linear-ds-vk
set -eu
cd "$(dirname "$0")"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

cat > "$TMP/t.vert" <<'EOF'
#version 450
void main() {
    vec2 p[3] = vec2[](vec2(-1,-3), vec2(-1,1), vec2(3,1));
    gl_Position = vec4(p[gl_VertexIndex], 0, 1);
}
EOF
cat > "$TMP/t.frag" <<'EOF'
#version 450
layout(location=0) out vec4 c;
void main() { c = vec4(0, 1, 0, 1); }
EOF
glslangValidator -V "$TMP/t.vert" -o "$TMP/vs.spv" >/dev/null
glslangValidator -V "$TMP/t.frag" -o "$TMP/fs.spv" >/dev/null

{
  echo "/* generated by build-kk-linear-ds-vk.sh */"
  echo "static const uint32_t vs_spv[] = {"
  xxd -e -g4 "$TMP/vs.spv" | awk '{for(i=2;i<=NF-1 && i<=5;i++) printf "0x%s,", $i; print ""}' | sed 's/0x,//g'
  echo "};"
  echo "static const uint32_t fs_spv[] = {"
  xxd -e -g4 "$TMP/fs.spv" | awk '{for(i=2;i<=NF-1 && i<=5;i++) printf "0x%s,", $i; print ""}' | sed 's/0x,//g'
  echo "};"
} > kk-linear-ds-vk-spv.h

VULKAN_PREFIX=$(brew --prefix vulkan-loader)
cc -O1 -o kk-linear-ds-vk kk-linear-ds-vk.c \
   -I"$(brew --prefix vulkan-headers)/include" \
   -L"$VULKAN_PREFIX/lib" -lvulkan -framework IOSurface -framework CoreFoundation
echo "built ./kk-linear-ds-vk"
