// SPDX-License-Identifier: GPL-2.0-only WITH LicenseRef-limina-exception
// Copyright © 2026 Gustavo Noronha Silva

/*
 * kk-linear-ds-vk: HOST-side Vulkan repro hunt for the KK linear+DS draw-drop.
 *
 * Renders clear(red) + one full-screen green triangle into a 256x256 BGRA8 color
 * attachment, in four configurations:
 *   1. tiling=OPTIMAL, no DS attachment
 *   2. tiling=OPTIMAL, D32S8 DS attachment (stencil compare ALWAYS, depth test off)
 *   3. tiling=LINEAR,  no DS
 *   4. tiling=LINEAR,  D32S8 DS         <-- the in-guest failing combo
 * Readback via vkCmdCopyImageToBuffer; PASS = center green, FAIL = red (clear only).
 *
 * Run against KosmicKrisp directly (no VM/venus/zink):
 *   VK_ICD_FILENAMES=$(ls /Volumes/mesa-cs/build-kk/src/kosmickrisp/vulkan/*.json) ./kk-linear-ds-vk
 * A failure here = pure KK bug, iterable host-side in seconds.
 *
 * Build: see build-kk-linear-ds-vk.sh (compiles shaders with glslangValidator, links
 * against the Homebrew Vulkan loader).
 */
#include <vulkan/vulkan.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef __APPLE__
#include <IOSurface/IOSurfaceRef.h>
#include <CoreFoundation/CoreFoundation.h>
#endif

#include "kk-linear-ds-vk-spv.h" /* vs_spv[], fs_spv[] generated by the build script */

#define W 256
#define H 256
#define CHECK(x)                                                                         \
   do {                                                                                  \
      VkResult r__ = (x);                                                                \
      if (r__ != VK_SUCCESS) {                                                           \
         fprintf(stderr, "%s:%d: %s = %d\n", __FILE__, __LINE__, #x, r__);               \
         exit(1);                                                                        \
      }                                                                                  \
   } while (0)

static uint32_t
find_mem_type(VkPhysicalDevice pdev, uint32_t bits, VkMemoryPropertyFlags want)
{
   VkPhysicalDeviceMemoryProperties mp;
   vkGetPhysicalDeviceMemoryProperties(pdev, &mp);
   for (uint32_t i = 0; i < mp.memoryTypeCount; i++)
      if ((bits & (1u << i)) && (mp.memoryTypes[i].propertyFlags & want) == want)
         return i;
   fprintf(stderr, "no memory type for bits=0x%x want=0x%x\n", bits, want);
   exit(1);
}

static VkDeviceMemory
alloc_bind_image(VkDevice dev, VkPhysicalDevice pdev, VkImage img,
                 VkMemoryPropertyFlags want)
{
   VkMemoryRequirements req;
   vkGetImageMemoryRequirements(dev, img, &req);
   VkMemoryAllocateInfo mai = {
      .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
      .allocationSize = req.size,
      .memoryTypeIndex = find_mem_type(pdev, req.memoryTypeBits, want),
   };
   VkDeviceMemory mem;
   CHECK(vkAllocateMemory(dev, &mai, NULL, &mem));
   CHECK(vkBindImageMemory(dev, img, mem, 0));
   return mem;
}

#ifdef __APPLE__
/* IOSurface whose bytes back the linear image via VK_EXT_external_memory_host —
 * the exact limina/vkr scanout provenance. Pitch must equal the driver's rowPitch. */
static void *
make_iosurface_base(uint32_t bpr, uint64_t *alloc_size)
{
   int32_t w = W, h = H, bpe = 4, pitch = bpr;
   uint32_t fmt = 'BGRA';
   CFNumberRef nw = CFNumberCreate(NULL, kCFNumberSInt32Type, &w);
   CFNumberRef nh = CFNumberCreate(NULL, kCFNumberSInt32Type, &h);
   CFNumberRef nb = CFNumberCreate(NULL, kCFNumberSInt32Type, &bpe);
   CFNumberRef np = CFNumberCreate(NULL, kCFNumberSInt32Type, &pitch);
   CFNumberRef nf = CFNumberCreate(NULL, kCFNumberSInt32Type, (int32_t *)&fmt);
   const void *keys[] = { kIOSurfaceWidth, kIOSurfaceHeight, kIOSurfaceBytesPerElement,
                          kIOSurfaceBytesPerRow, kIOSurfacePixelFormat };
   const void *vals[] = { nw, nh, nb, np, nf };
   CFDictionaryRef props = CFDictionaryCreate(NULL, keys, vals, 5,
                                              &kCFTypeDictionaryKeyCallBacks,
                                              &kCFTypeDictionaryValueCallBacks);
   IOSurfaceRef io = IOSurfaceCreate(props);
   if (!io) { fprintf(stderr, "IOSurfaceCreate failed\n"); exit(1); }
   *alloc_size = IOSurfaceGetAllocSize(io);
   return IOSurfaceGetBaseAddress(io); /* surface intentionally leaked (kept alive) */
}
#endif

static int
run_case(VkPhysicalDevice pdev, VkDevice dev, VkQueue q, uint32_t qfam,
         VkImageTiling tiling, int with_ds, int import_iosurface)
{
   /* color image */
   VkImageCreateInfo ici = {
      .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
      .imageType = VK_IMAGE_TYPE_2D,
      .format = VK_FORMAT_B8G8R8A8_UNORM,
      .extent = { W, H, 1 },
      .mipLevels = 1,
      .arrayLayers = 1,
      .samples = VK_SAMPLE_COUNT_1_BIT,
      .tiling = tiling,
      .usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT |
               VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
      .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
   };
   VkImage color;
   CHECK(vkCreateImage(dev, &ici, NULL, &color));
   VkDeviceMemory cmem;
   if (!import_iosurface) {
      cmem = alloc_bind_image(dev, pdev, color, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
   } else {
#ifdef __APPLE__
      VkSubresourceLayout lay;
      VkImageSubresource sub = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0 };
      vkGetImageSubresourceLayout(dev, color, &sub, &lay);
      uint64_t alloc_size = 0;
      void *base = make_iosurface_base((uint32_t)lay.rowPitch, &alloc_size);
      VkMemoryRequirements req;
      vkGetImageMemoryRequirements(dev, color, &req);
      VkMemoryDedicatedAllocateInfo ded = {
         .sType = VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO,
         .image = color,
      };
      VkImportMemoryHostPointerInfoEXT imp = {
         .sType = VK_STRUCTURE_TYPE_IMPORT_MEMORY_HOST_POINTER_INFO_EXT,
         .pNext = &ded,
         .handleType = VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT,
         .pHostPointer = base,
      };
      uint64_t size = req.size > alloc_size ? req.size : alloc_size;
      VkMemoryAllocateInfo mai = {
         .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
         .pNext = &imp,
         .allocationSize = size,
         .memoryTypeIndex =
            find_mem_type(pdev, req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT),
      };
      CHECK(vkAllocateMemory(dev, &mai, NULL, &cmem));
      CHECK(vkBindImageMemory(dev, color, cmem, 0));
#else
      fprintf(stderr, "iosurface import requires __APPLE__\n");
      exit(1);
#endif
   }

   VkImageViewCreateInfo vci = {
      .sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
      .image = color,
      .viewType = VK_IMAGE_VIEW_TYPE_2D,
      .format = ici.format,
      .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 },
   };
   VkImageView cview;
   CHECK(vkCreateImageView(dev, &vci, NULL, &cview));

   /* optional DS image */
   VkImage ds = VK_NULL_HANDLE;
   VkDeviceMemory dsmem = VK_NULL_HANDLE;
   VkImageView dsview = VK_NULL_HANDLE;
   const VkFormat dsfmt = VK_FORMAT_D32_SFLOAT_S8_UINT;
   if (with_ds) {
      VkImageCreateInfo dsi = ici;
      dsi.format = dsfmt;
      dsi.tiling = VK_IMAGE_TILING_OPTIMAL;
      dsi.usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;
      CHECK(vkCreateImage(dev, &dsi, NULL, &ds));
      dsmem = alloc_bind_image(dev, pdev, ds, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
      VkImageViewCreateInfo dvci = vci;
      dvci.image = ds;
      dvci.format = dsfmt;
      dvci.subresourceRange.aspectMask =
         VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT;
      CHECK(vkCreateImageView(dev, &dvci, NULL, &dsview));
   }

   /* readback buffer */
   VkBufferCreateInfo bci = {
      .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
      .size = W * H * 4,
      .usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT,
   };
   VkBuffer rb;
   CHECK(vkCreateBuffer(dev, &bci, NULL, &rb));
   VkMemoryRequirements breq;
   vkGetBufferMemoryRequirements(dev, rb, &breq);
   VkMemoryAllocateInfo bai = {
      .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
      .allocationSize = breq.size,
      .memoryTypeIndex = find_mem_type(pdev, breq.memoryTypeBits,
                                       VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                          VK_MEMORY_PROPERTY_HOST_COHERENT_BIT),
   };
   VkDeviceMemory bmem;
   CHECK(vkAllocateMemory(dev, &bai, NULL, &bmem));
   CHECK(vkBindBufferMemory(dev, rb, bmem, 0));

   /* shaders + pipeline (dynamic rendering) */
   VkShaderModuleCreateInfo smci = {
      .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
      .codeSize = sizeof(vs_spv),
      .pCode = vs_spv,
   };
   VkShaderModule vs, fs;
   CHECK(vkCreateShaderModule(dev, &smci, NULL, &vs));
   smci.codeSize = sizeof(fs_spv);
   smci.pCode = fs_spv;
   CHECK(vkCreateShaderModule(dev, &smci, NULL, &fs));

   VkPipelineLayoutCreateInfo plci = {
      .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
   };
   VkPipelineLayout layout;
   CHECK(vkCreatePipelineLayout(dev, &plci, NULL, &layout));

   VkPipelineShaderStageCreateInfo stages[2] = {
      { .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
        .stage = VK_SHADER_STAGE_VERTEX_BIT, .module = vs, .pName = "main" },
      { .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
        .stage = VK_SHADER_STAGE_FRAGMENT_BIT, .module = fs, .pName = "main" },
   };
   VkPipelineVertexInputStateCreateInfo vin = {
      .sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
   };
   VkPipelineInputAssemblyStateCreateInfo ia = {
      .sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
      .topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
   };
   VkViewport vp = { 0, 0, W, H, 0, 1 };
   VkRect2D sc = { { 0, 0 }, { W, H } };
   VkPipelineViewportStateCreateInfo vps = {
      .sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
      .viewportCount = 1, .pViewports = &vp, .scissorCount = 1, .pScissors = &sc,
   };
   VkPipelineRasterizationStateCreateInfo rs = {
      .sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
      .polygonMode = VK_POLYGON_MODE_FILL,
      .cullMode = VK_CULL_MODE_NONE,
      .lineWidth = 1.0f,
   };
   VkPipelineMultisampleStateCreateInfo ms = {
      .sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
      .rasterizationSamples = VK_SAMPLE_COUNT_1_BIT,
   };
   VkStencilOpState sop = {
      .failOp = VK_STENCIL_OP_KEEP,
      .passOp = VK_STENCIL_OP_KEEP,
      .depthFailOp = VK_STENCIL_OP_KEEP,
      .compareOp = VK_COMPARE_OP_ALWAYS,
      .compareMask = 0xff,
      .writeMask = 0xff,
   };
   VkPipelineDepthStencilStateCreateInfo dss = {
      .sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO,
      .depthTestEnable = VK_FALSE,
      .depthWriteEnable = VK_FALSE,
      .stencilTestEnable = with_ds ? VK_TRUE : VK_FALSE,
      .front = sop,
      .back = sop,
   };
   VkPipelineColorBlendAttachmentState cba = {
      .colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                        VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT,
   };
   VkPipelineColorBlendStateCreateInfo cb = {
      .sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
      .attachmentCount = 1,
      .pAttachments = &cba,
   };
   VkPipelineRenderingCreateInfo prci = {
      .sType = VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO,
      .colorAttachmentCount = 1,
      .pColorAttachmentFormats = &ici.format,
      .depthAttachmentFormat = with_ds ? dsfmt : VK_FORMAT_UNDEFINED,
      .stencilAttachmentFormat = with_ds ? dsfmt : VK_FORMAT_UNDEFINED,
   };
   VkGraphicsPipelineCreateInfo gpci = {
      .sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
      .pNext = &prci,
      .stageCount = 2,
      .pStages = stages,
      .pVertexInputState = &vin,
      .pInputAssemblyState = &ia,
      .pViewportState = &vps,
      .pRasterizationState = &rs,
      .pMultisampleState = &ms,
      .pDepthStencilState = &dss,
      .pColorBlendState = &cb,
      .layout = layout,
   };
   VkPipeline pipe;
   CHECK(vkCreateGraphicsPipelines(dev, VK_NULL_HANDLE, 1, &gpci, NULL, &pipe));

   /* record */
   VkCommandPoolCreateInfo cpci = {
      .sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
      .queueFamilyIndex = qfam,
   };
   VkCommandPool pool;
   CHECK(vkCreateCommandPool(dev, &cpci, NULL, &pool));
   VkCommandBufferAllocateInfo cbai = {
      .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
      .commandPool = pool,
      .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
      .commandBufferCount = 1,
   };
   VkCommandBuffer cmd;
   CHECK(vkAllocateCommandBuffers(dev, &cbai, &cmd));
   VkCommandBufferBeginInfo cbbi = {
      .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
   };
   CHECK(vkBeginCommandBuffer(cmd, &cbbi));

   VkImageMemoryBarrier to_color = {
      .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
      .srcAccessMask = 0,
      .dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
      .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED,
      .newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
      .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
      .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
      .image = color,
      .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 },
   };
   vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                        VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, 0, 0, NULL, 0,
                        NULL, 1, &to_color);
   if (with_ds) {
      VkImageMemoryBarrier to_ds = to_color;
      to_ds.dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
      to_ds.newLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
      to_ds.image = ds;
      to_ds.subresourceRange.aspectMask =
         VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT;
      vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                           VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT, 0, 0, NULL, 0,
                           NULL, 1, &to_ds);
   }

   VkRenderingAttachmentInfo catt = {
      .sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO,
      .imageView = cview,
      .imageLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
      .loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
      .storeOp = VK_ATTACHMENT_STORE_OP_STORE,
      .clearValue = { .color = { .float32 = { 1, 0, 0, 1 } } },
   };
   VkRenderingAttachmentInfo datt = {
      .sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO,
      .imageView = dsview,
      .imageLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
      .loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
      .storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
      .clearValue = { .depthStencil = { 1.0f, 0 } },
   };
   VkRenderingInfo ri = {
      .sType = VK_STRUCTURE_TYPE_RENDERING_INFO,
      .renderArea = { { 0, 0 }, { W, H } },
      .layerCount = 1,
      .colorAttachmentCount = 1,
      .pColorAttachments = &catt,
      .pDepthAttachment = with_ds ? &datt : NULL,
      .pStencilAttachment = with_ds ? &datt : NULL,
   };
   vkCmdBeginRendering(cmd, &ri);
   vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipe);
   vkCmdDraw(cmd, 3, 1, 0, 0);
   vkCmdEndRendering(cmd);

   VkImageMemoryBarrier to_src = to_color;
   to_src.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
   to_src.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
   to_src.oldLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
   to_src.newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
   vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                        VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, NULL, 0, NULL, 1,
                        &to_src);
   VkBufferImageCopy region = {
      .imageSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 },
      .imageExtent = { W, H, 1 },
   };
   vkCmdCopyImageToBuffer(cmd, color, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, rb, 1,
                          &region);
   CHECK(vkEndCommandBuffer(cmd));

   VkSubmitInfo si = {
      .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
      .commandBufferCount = 1,
      .pCommandBuffers = &cmd,
   };
   CHECK(vkQueueSubmit(q, 1, &si, VK_NULL_HANDLE));
   CHECK(vkQueueWaitIdle(q));

   unsigned char *px;
   CHECK(vkMapMemory(dev, bmem, 0, VK_WHOLE_SIZE, 0, (void **)&px));
   unsigned mid = (H / 2) * W * 4 + (W / 2) * 4; /* BGRA */
   int b = px[mid], g = px[mid + 1], r = px[mid + 2];
   const char *verdict = g > 200 ? "DRAW LANDED (green)"
                         : r > 200 ? "DRAW DROPPED (clear-only red)"
                                   : "UNEXPECTED";
   printf("tiling=%s ds=%d iosurface=%d: center=(r:%d g:%d b:%d) -> %s\n",
          tiling == VK_IMAGE_TILING_LINEAR ? "LINEAR " : "OPTIMAL", with_ds,
          import_iosurface, r, g, b, verdict);
   vkUnmapMemory(dev, bmem);

   /* leak everything; process exits per matrix anyway */
   (void)cmem; (void)dsmem;
   return g > 200 ? 0 : 1;
}

int
main(void)
{
   VkApplicationInfo app = {
      .sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
      .apiVersion = VK_API_VERSION_1_3,
   };
   VkInstanceCreateInfo ici = {
      .sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
      .pApplicationInfo = &app,
   };
   VkInstance inst;
   CHECK(vkCreateInstance(&ici, NULL, &inst));

   uint32_t n = 1;
   VkPhysicalDevice pdev;
   CHECK(vkEnumeratePhysicalDevices(inst, &n, &pdev));
   VkPhysicalDeviceProperties props;
   vkGetPhysicalDeviceProperties(pdev, &props);
   printf("device: %s (api %u.%u.%u)\n", props.deviceName,
          VK_API_VERSION_MAJOR(props.apiVersion), VK_API_VERSION_MINOR(props.apiVersion),
          VK_API_VERSION_PATCH(props.apiVersion));

   uint32_t qn = 0;
   vkGetPhysicalDeviceQueueFamilyProperties(pdev, &qn, NULL);
   VkQueueFamilyProperties qprops[8];
   qn = qn > 8 ? 8 : qn;
   vkGetPhysicalDeviceQueueFamilyProperties(pdev, &qn, qprops);
   uint32_t qfam = 0;
   for (uint32_t i = 0; i < qn; i++)
      if (qprops[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) { qfam = i; break; }

   float prio = 1.0f;
   VkDeviceQueueCreateInfo qci = {
      .sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
      .queueFamilyIndex = qfam,
      .queueCount = 1,
      .pQueuePriorities = &prio,
   };
   VkPhysicalDeviceDynamicRenderingFeatures dynr = {
      .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_FEATURES,
      .dynamicRendering = VK_TRUE,
   };
   const char *dev_exts[] = { "VK_EXT_external_memory_host" };
   VkDeviceCreateInfo dci = {
      .sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
      .pNext = &dynr,
      .queueCreateInfoCount = 1,
      .pQueueCreateInfos = &qci,
      .enabledExtensionCount = 1,
      .ppEnabledExtensionNames = dev_exts,
   };
   VkDevice dev;
   CHECK(vkCreateDevice(pdev, &dci, NULL, &dev));
   VkQueue q;
   vkGetDeviceQueue(dev, qfam, 0, &q);

   int fails = 0;
   fails += run_case(pdev, dev, q, qfam, VK_IMAGE_TILING_OPTIMAL, 0, 0);
   fails += run_case(pdev, dev, q, qfam, VK_IMAGE_TILING_OPTIMAL, 1, 0);
   fails += run_case(pdev, dev, q, qfam, VK_IMAGE_TILING_LINEAR, 0, 0);
   fails += run_case(pdev, dev, q, qfam, VK_IMAGE_TILING_LINEAR, 1, 0);
   fails += run_case(pdev, dev, q, qfam, VK_IMAGE_TILING_LINEAR, 0, 1);
   fails += run_case(pdev, dev, q, qfam, VK_IMAGE_TILING_LINEAR, 1, 1);
   return fails;
}
